# UV Configuration for MCP Manager
# Enforces system Python 3.13 usage (Constitutional Requirement)
#
# This configuration prevents UV from downloading or installing additional
# Python interpreters, ensuring exclusive use of the system Python 3.13.
#
# References:
# - Constitution: System Python enforcement
# - Feature: 002-system-python-enforcement
# - Research: specs/002-system-python-enforcement/research.md lines 306-337

# CRITICAL: Prevent UV from downloading any Python interpreters
# Setting: "never" ensures UV will not download Python interpreters under any circumstances
python-downloads = "never"

# CRITICAL: Force UV to use only system-installed Python
# Setting: "only-system" prevents UV from using managed or downloaded Python interpreters
python-preference = "only-system"
