# DISABLED - All CI runs locally to avoid GitHub Actions costs
# Enable only if you have free GitHub Actions minutes
name: CI Validation (DISABLED)

on:
  workflow_dispatch:  # Only manual trigger to avoid costs

jobs:
  validate:
    name: Validate Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Node dependencies
        run: npm ci

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff mypy pytest pytest-cov
          pip install -e .

      - name: Check branch naming
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Checking branch: $BRANCH"
          ./scripts/check-branch-name.sh

      - name: Python formatting check
        run: black src/ tests/ --check

      - name: Python linting
        run: ruff check src/ tests/

      - name: Python type checking
        run: mypy src/

      - name: Python tests
        run: pytest tests/ --cov=mcp_manager --cov-fail-under=80

      - name: Astro type check
        run: npm run check

      - name: Build website
        run: npm run build

      - name: Verify build outputs
        run: |
          test -d ./docs || exit 1
          test -f ./docs/.nojekyll || exit 1
          test -d ./docs/_astro || exit 1
          echo "✅ Build outputs verified"

      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs-preview
          path: docs/
          retention-days: 7

      - name: PR Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **CI Validation Passed!**\n\nAll checks completed successfully. Docs preview artifact available for 7 days.'
            })